fix: pass 2-tuples to Analysis(datas=) not 3-tuples
Analysis(datas=...) API expects (src_path, dest_path) 2-tuples.
The internal format (dest, src, 'DATA') is only valid inside a.datas
after normalization. Passing 3-tuples caused:
  ValueError: too many values to unpack (expected 2)

Also consolidated frontend dist/ data collection into the same
_USER_DATAS list instead of appending to a.datas post-hoc.